# Generated by Django 4.2.14 on 2024-08-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_image_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="头像URL"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女"), ("unknow", "未知")],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="手机号"
            ),
        ),
    ]
